services:
  database:
    image: postgres:latest
    container_name: ffi-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ffiContracting
      POSTGRES_PASSWORD: Jffi2024
      POSTGRES_DB: ffidb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./
    depends_on:
      - database
    volumes:
      - ./:/app
    ports:
      - "8000:8000" # HTTP Port
      - "5678:5678" # Debug Port
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      python -m debugpy
      --listen 0.0.0.0:5678
      --wait-for-client
      -m uvicorn app.main:app 
      --host 0.0.0.0
      --port 8000
      --reload 

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/src          # mount entire project
      - node_modules:/src/node_modules   # prevent node_modules overwrite

    ports:
      - "3000:3000"
      - "9229:9229" # Debug Port
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PRIVATE_WATCHPACK_POLLING=true


volumes:
  pgdata:
  node_modules:
